# Generated by Django 5.2.6 on 2025-09-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_constancia_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='dptos',
            fields=[
                ('idDepto', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombreDepto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='municipios',
            fields=[
                ('idMpio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMpio', models.CharField(max_length=100)),
                ('nombreCentro', models.CharField(blank=True, max_length=100, null=True)),
                ('idDepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dptos')),
            ],
        ),
    ]
